# Generated by Django 2.2.1 on 2019-05-23 10:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hlPY', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course_python_basic',
            name='basic_image',
            field=models.CharField(default='pictures\\logo.png', max_length=255),
        ),
        migrations.AddField(
            model_name='course_python_practice',
            name='practice_image',
            field=models.CharField(default='pictures\\logo.png', max_length=255),
        ),
        migrations.AddField(
            model_name='user_tool',
            name='tool_image',
            field=models.CharField(default='pictures\\logo.png', max_length=255),
        ),
        migrations.AlterField(
            model_name='practice_learn_progress',
            name='progress_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user_tool',
            name='conform_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 23, 10, 48, 56, 824692)),
        ),
        migrations.AlterField(
            model_name='user_tool',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 23, 10, 48, 56, 824692)),
        ),
        migrations.AlterField(
            model_name='user_tool',
            name='download_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user_tool',
            name='tool_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user_tool',
            name='tool_price',
            field=models.IntegerField(default=0),
        ),
    ]
